port:  5000
markdown: kramdown
name: "Data Jobs"
baseurl: https://rebeccawilliams.us
url: https://rebeccawilliams.us/datajobs
encoding: utf-8
timezone: America/Chicago
description: "Search government data jobs"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyAVQrWzBeHiKaOiNwkEyLkxDV8-jUbTmTw
